// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Add(arg1:main.PortForward):Promise<void>;

export function BatchAdd(arg1:Array<main.PortForward>):Promise<void>;

export function BatchDelete(arg1:Array<main.PortForward>):Promise<void>;

export function Delete(arg1:main.PortForward):Promise<void>;

export function Get():Promise<Array<main.PortForward>>;
