// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Add(arg1) {
  return window['go']['main']['ApiPortForwarder']['Add'](arg1);
}

export function BatchAdd(arg1) {
  return window['go']['main']['ApiPortForwarder']['BatchAdd'](arg1);
}

export function BatchDelete(arg1) {
  return window['go']['main']['ApiPortForwarder']['BatchDelete'](arg1);
}

export function Delete(arg1) {
  return window['go']['main']['ApiPortForwarder']['Delete'](arg1);
}

export function Get() {
  return window['go']['main']['ApiPortForwarder']['Get']();
}
